import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
const here=path.dirname(fileURLToPath(import.meta.url));
const target=process.argv[2];
if(!target)throw new Error('Pass the SU7 model directory.');
const model=await fs.readFile(path.join(target,'Xiaomi_SU7_Max.glb'));
const jsonLength=model.readUInt32LE(12);
const gltf=JSON.parse(model.subarray(20,20+jsonLength).toString('utf8'));
if((gltf.buffers||[]).some(b=>b.uri)||(gltf.images||[]).some(i=>i.uri&&!i.uri.startsWith('data:')))throw new Error('Model has external resources.');
const result=await build({entryPoints:[path.join(here,'app.js')],bundle:true,minify:true,format:'iife',platform:'browser',target:['es2020'],legalComments:'inline',write:false});
const script=result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
const poster=await fs.readFile(path.join(target,'renders','front_hero.png'));
const license=await fs.readFile(path.join(here,'node_modules','three','LICENSE'),'utf8');
let html=await fs.readFile(path.join(here,'viewer.html'),'utf8');
for(const [key,value] of Object.entries({__POSTER__:poster.toString('base64'),__MODEL__:model.toString('base64'),__BUNDLE__:script,__LICENSE__:license.replace(/-->/g,'-- >')}))html=html.replace(key,()=>value);
const output=path.join(target,'Xiaomi_SU7_Viewer.html');await fs.writeFile(output,html);
console.log(JSON.stringify({output,bytes:Buffer.byteLength(html),embeddedModelBytes:model.length,modelMeshes:gltf.meshes.length,bundleBytes:Buffer.byteLength(script),offline:true},null,2));
