const {chromium}=require('C:/Users/admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file:///'+path.resolve('FORM_FLOW.html').replaceAll('\\','/'));
 await page.waitForFunction(()=>document.querySelector('video').readyState>=1);
 console.log('Metadata',await page.locator('video').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight})));
 await page.screenshot({path:'FORM_FLOW/page-desktop.png',fullPage:true});
 await page.locator('.chapter[data-time="5.625"]').click();
 await page.waitForFunction(()=>Math.abs(document.querySelector('video').currentTime-5.625)<.05);
 console.log('Seek',await page.locator('video').evaluate(v=>v.currentTime));
 await page.locator('video').evaluate(v=>v.play());
 await page.waitForFunction(()=>document.querySelector('video').currentTime>5.8);
 await page.locator('video').evaluate(v=>v.pause());
 console.log('Playback passed');
 await page.locator('summary').click();
 const actualSource=await page.locator('#source-code').textContent();
 const expectedSource=fs.readFileSync('render_showreel.py','utf8').replaceAll('\r\n','\n');
 if(actualSource!==expectedSource)throw Error('Embedded source mismatch');
 console.log('Embedded Python source matches');
 await page.setViewportSize({width:390,height:844});
 await page.locator('summary').click();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'FORM_FLOW/page-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 console.log('Mobile overflow',overflow,'Browser errors',errors);
 if(overflow||errors.length)throw Error('Browser verification failed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
