import pathlib,base64,html,ast,json,datetime,subprocess,sys
ROOT=pathlib.Path(__file__).parent.parent;OUT=ROOT/'liang_sicheng_dougong'
sys.path.insert(0,str(ROOT/'video_deps'));import imageio_ffmpeg
def esc(s):return html.escape(str(s))
def data(p,mime):return 'data:'+mime+';base64,'+base64.b64encode(p.read_bytes()).decode()
tree=ast.parse((ROOT/'scripts'/'make_video.py').read_text(encoding='utf-8'));scenes=next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='scenes' for t in n.targets))
metadata=json.loads((OUT/'3d_video_metadata.json').read_text());timeline=json.loads((OUT/'timeline_3d.json').read_text());video=ROOT/'dougong_3d_explained_bilingual.mp4'
check=subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),'-v','error','-i',str(video),'-f','null','-'],capture_output=True,text=True);assert check.returncode==0,check.stderr
rows=[];pos=0
for i,t in enumerate(timeline):
 idx=t['id'];rows.append(f'<tr><td>{i+1:02}</td><td>{pos:.1f}–{pos+t["seconds"]:.1f} 秒</td><td>{esc(scenes[idx][3])}</td><td>{esc(scenes[idx][2])}</td></tr>');pos+=t['seconds']
prompt='解读梁思成先生的《图像中国建筑史》其中一页(图像中国建筑史.jpg),再以生动的视频形式展示出来. 添加合适的音乐，请务必做到引人入胜，如果需要用到旁白或对话，用TTS合成，字幕用中英双语.'
preview=data(OUT/'3d_final_preview_00.jpg','image/jpeg');original=data(ROOT/'_build'/'pictorial_history_of_chinese_architecture.jpg','image/jpeg')
figures=''.join(f'<figure><img loading="lazy" src="{data(OUT/f"3d_final_preview_{n:02}.jpg","image/jpeg")}" alt="{esc(label)}"><figcaption>{esc(label)}</figcaption></figure>' for n,label in [(1,'三维分解：观察构件层次'),(3,'栌斗：柱头上的承接节点'),(5,'昂：观察斜向构件的空间位置')])
codes=''.join(f'<details><summary>{esc(label)} · 展开源码</summary><pre><code>{esc((ROOT/'scripts'/name).read_text(encoding="utf-8"))}</code></pre></details>' for name,label in [('build_3d_scene.py','三维建模与动画'),('render_3d_animation.py','渲染与镜头修正'),('finish_3d_video.py','插帧、混音与完整双语字幕')])
doc=f'''<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>一页看懂斗拱｜三维视频制作报告</title><style>
:root{{--ink:#17342c;--muted:#597066;--paper:#faf6ed;--gold:#a57839;--line:#dcd9ca}}*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;background:var(--paper);color:var(--ink);font:16px/1.8 "Microsoft YaHei",system-ui,sans-serif}}main{{max-width:1120px;margin:auto;padding:0 32px 70px}}header{{background:#102a23;color:#f8eddb;padding:54px 32px 44px}}header .inner{{max-width:1056px;margin:auto}}.eyebrow{{letter-spacing:.15em;color:#d3b27d;font-size:13px}}h1{{font-size:clamp(32px,5vw,52px);line-height:1.3;margin:15px 0}}header p{{max-width:760px;color:#d5dfd5}}nav{{display:flex;gap:22px;flex-wrap:wrap;border-bottom:1px solid var(--line);padding:20px 0}}a{{color:var(--gold)}}nav a{{color:var(--ink);text-decoration:none;font-size:14px}}section{{padding-top:40px}}h2{{font-size:27px;margin:0 0 16px}}h3{{font-size:19px;margin:25px 0 8px}}p{{margin:10px 0}}.stats{{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin:24px 0}}.stat{{background:#eeebdf;padding:18px;border-radius:9px}}.stat strong{{display:block;font-size:23px}}.stat span{{font-size:13px;color:var(--muted)}}video{{width:100%;display:block;background:#0c211b;border-radius:12px}}.note{{border-left:3px solid var(--gold);background:#f0eadc;padding:14px 20px;margin:18px 0}}blockquote{{margin:0;background:#fffdf7;padding:24px;border:1px solid var(--line);border-radius:8px}}.grid{{display:grid;grid-template-columns:1fr 1fr;gap:25px}}figure{{margin:0}}img{{max-width:100%;height:auto;border-radius:9px}}.source{{max-height:640px;display:block;margin:auto}}figcaption{{color:var(--muted);font-size:13px;padding:8px 0 15px}}.gallery{{display:grid;gap:20px;grid-template-columns:repeat(3,1fr)}}table{{border-collapse:collapse;width:100%;font-size:14px}}th,td{{text-align:left;padding:13px 14px;border-bottom:1px solid var(--line);vertical-align:top}}th{{background:#e8e5d8}}td:first-child{{white-space:nowrap;color:var(--gold)}}.table-wrap{{overflow:auto}}code{{font-family:Consolas,monospace;font-size:13px}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;background:#12251f;color:#dbe6d9;padding:22px;border-radius:8px;line-height:1.55}}details{{border:1px solid var(--line);border-radius:8px;padding:14px 18px;margin:12px 0}}summary{{cursor:pointer;font-weight:600}}footer{{border-top:1px solid var(--line);padding-top:20px;margin-top:45px;color:var(--muted);font-size:13px}}.badge{{display:inline-block;background:#e6eddf;color:#386442;padding:2px 10px;border-radius:20px;font-size:13px}}@media(max-width:760px){{main{{padding:0 18px 45px}}.stats{{grid-template-columns:1fr 1fr}}.grid,.gallery{{grid-template-columns:1fr}}header{{padding:36px 20px}}th,td{{min-width:95px}}}}@media print{{header{{background:white;color:#17342c}}header p{{color:#597066}}nav,video,details{{display:none}}section{{break-inside:avoid}}}}
</style></head><body><header><div class="inner"><div class="eyebrow">梁思成 · 《图像中国建筑史》 · 制作档案</div><h1>让一页建筑图，获得空间感</h1><p>从原页细读到木质三维结构：用环绕镜头、构件分解与重点高亮，解释斗拱如何组织屋檐、柱与柱础。</p></div></header><main>
<nav aria-label="报告目录"><a href="#result">成片</a><a href="#prompt">提示词与需求</a><a href="#reading">书页解读</a><a href="#implementation">实现细节</a><a href="#storyboard">分镜与旁白</a><a href="#validation">验证与交付</a></nav>
<section id="result"><h2>成片与观看方式</h2><p>新版采用木质外观与重点构件高亮，三维模型成为画面主体。视频、示例图和本报告样式全部嵌入本 HTML；将文件单独复制到其他位置，仍可离线阅读和播放。</p><div class="stats"><div class="stat"><strong>{metadata['duration']:.1f} 秒</strong><span>新版时长</span></div><div class="stat"><strong>1280 × 720</strong><span>视频分辨率</span></div><div class="stat"><strong>9 段</strong><span>三维讲解章节</span></div><div class="stat"><strong>中文＋英文</strong><span>完整旁白双语字幕</span></div></div><video controls preload="none" playsinline poster="{preview}"><source src="{data(video,'video/mp4')}" type="video/mp4">浏览器不支持 HTML 视频播放，请使用 MP4 成片。</video><p class="note">解说是现代教学释读，不是梁思成先生的原话。三维模型依据单页所示构件关系建立，使用示意尺寸；没有进行测绘、榫卯考据或结构计算。</p></section>
<section id="prompt"><h2>提示词与需求记录</h2><h3>原始提示词</h3><blockquote>{esc(prompt)}</blockquote><h3>后续指令</h3><table><thead><tr><th>指令</th><th>落实方式</th></tr></thead><tbody><tr><td>use english for folder name and file name</td><td>产物与脚本使用英文文件名，报告正文保持中文。</td></tr><tr><td>Move dougong_explained_bilingual.mp4 to root folder.</td><td>二维初版已移到工作区根目录；三维新版也交付在根目录。</td></tr><tr><td>generate a standalone HTML report with prompt and implementation details in Chinese language</td><td>生成本独立 HTML 报告，记录提示词、实际实现、源码与验证结果。</td></tr><tr><td>I viewed the MP4 file, not up to my standards. Need 3D view of the structure</td><td>由二维原图特写升级为三维模型、环绕镜头、构件分解与组装。</td></tr><tr><td>视觉风格选择：3</td><td>木质外观＋重点构件高亮。</td></tr></tbody></table><h3>据此整理的制作任务</h3><p>以“屋檐为什么能伸出柱子”为开场悬念，从整体结构进入柱头节点，再辨认栌斗、华拱、昂与三跳；使用三维空间视角解释交叉与承接关系，以中文 TTS 旁白、原创五声音阶配乐和中英字幕完成短片。</p></section>
<section id="reading"><h2>这一页在讲什么</h2><div class="grid"><figure><img class="source" src="{original}" alt="用户提供的中国建筑之ORDER原页"><figcaption>用户提供的原页；原始文件现命名为 pictorial_history_of_chinese_architecture.jpg。</figcaption></figure><div><h3>中国建筑之“ORDER”</h3><p>页底标题为 The Chinese “Order”。这张图将斗拱、柱与柱础放入同一结构视图，展现构件的名称、层次和组合。片中把 ORDER 解释为构件组合的秩序，而非直接套用西方古典柱式概念。</p><h3>三跳：一华拱，两昂</h3><p>页旁文字明确指出：图示斗拱为三跳，由一华拱与两昂组成。“跳”描述向外挑出的层次，不能通过木块数量直接计数。</p><h3>材：比例的共同基准</h3><p>页旁说明各部尺寸可用“材”以及它的倍数或分数来度量。视频由此介绍模数思想；模型的尺寸比例只是教学表达，并未据此声称完成历史尺度复原。</p><h3>沿构件追踪重量</h3><p>视频用屋面→梁枋及斗拱等构件→柱→柱础与地基，组织简化的受力叙事。这条路径用于帮助理解，不能代替完整的力学分析。</p></div></div><table><thead><tr><th>原页编号</th><th>名称</th><th>视频中的作用</th></tr></thead><tbody><tr><td>20</td><td>栌斗</td><td>定位柱头的主要承接节点。</td></tr><tr><td>19</td><td>华拱</td><td>解释向外出跳的第一层构件。</td></tr><tr><td>17</td><td>昂</td><td>辨认斜向构件及其空间位置。</td></tr><tr><td>24 / 26</td><td>柱 / 柱础</td><td>建立上部构件与下部支承的联系。</td></tr><tr><td>1 / 2 / 3</td><td>飞椽 / 檐椽 / 橑檐枋</td><td>组织模型顶部的屋檐构件。</td></tr></tbody></table></section>
<section id="implementation"><h2>实际实现方式</h2><div class="gallery">{figures}</div><h3>三维几何与木质材质</h3><p>使用 Blender 3.6 的 Python API 建立真实网格模型。柱和柱础由圆柱体组成；斗以底小顶大的体块和承接座表达；拱采用有起伏下缘的挤出截面；昂由斜向梁体表达。顶部设置橑檐枋、椽与板件，使镜头能观察斗拱和屋檐的联系。构件边缘添加倒角与加权法线，减弱生硬的立方体感。</p><p>木纹通过程序化噪声、方向缩放、颜色渐变和轻微凹凸生成，未使用 AI 生成图片或三维生成服务。琥珀色用于栌斗、华拱等重点，青绿色用于昂等构件；高亮随章节渐入渐出。</p><h3>镜头、分解与组装</h3><p>相机围绕模型移动，交替采用全景和柱头近景。分解段对不同构件组施加不同的竖向位移，随后恢复组装位置；全景镜头扩大取景范围，保留分解后的主要构件。相机位置和旋转采用关键帧动画，构件位移使用平滑过渡。</p><h3>渲染与视频合成</h3><p>使用 EEVEE 渲染、16 个抗锯齿采样、环境遮蔽、柔和阴影与三盏面积光。基础动画时间线为每秒 12 帧，实际每隔 4 帧渲染一张，即每秒 3 张三维画面，为控制计算量，插帧在 640 × 360 尺寸计算，再通过 Lanczos 放大到 1280 × 720，输出 24 帧/秒。插帧提高镜头流畅性，快速遮挡变化处仍可能出现插帧痕迹。</p><p>用 Pillow 在三维画面上叠加章节标题、字幕底板、教学模型说明和进度条。最终编码为 H.264 / yuv420p，音轨为 AAC 192 kb/s，并启用 faststart。</p><h3>中文 TTS、字幕与配乐</h3><p>中文旁白使用 edge-tts 的 zh-CN-YunxiNeural 声线，语速为 +2%。保留已合成的语音，转为 24 kHz 单声道后按新版章节重新编排；每段前后分别留出约 0.35 秒与 0.65 秒空白。</p><p>新版字幕覆盖完整旁白内容，并配有对应英文译文。字幕按语句长度估算分段时间，没有采用逐词时间戳，因此个别字幕切换与口语停顿可能存在少量偏差。视频烧录字幕，同时另附 SRT。</p><p>配乐由代码合成：五声音阶音列配合递减谐波形成拨弦音色，叠加低频持续音；开头和结尾设置淡入淡出，旁白出现时降低配乐电平。该音色是合成拨弦，不是实录古琴或古筝。</p><h3>制作源码</h3><p>以下源码直接嵌入报告，可离线展开查阅。重制需要 Blender、Python、Pillow、NumPy、edge-tts、imageio-ffmpeg、原页图片，以及旁白缓存或可连接的 TTS 服务。</p>{codes}</section>
<section id="storyboard"><h2>分镜与中文旁白</h2><p>时间为实际成片章节边界，单位为秒。首版的十三个二维章节，在新版中收束为九段三维讲解。</p><div class="table-wrap"><table><thead><tr><th>序号</th><th>时间</th><th>章节</th><th>中文旁白</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div></section>
<section id="validation"><h2>验证结果与文件交付</h2><p><span class="badge">完整解码通过</span> 最终 MP4 已使用 FFmpeg 从头到尾解码，返回码为 0。三维预览与合成画面经过人工视觉检查。混音浮点峰值为 {metadata['audio_peak']:.3f}，低于 1.0；此处表示数字峰值检查，不代表完成专业响度母带处理。</p><table><thead><tr><th>文件</th><th>用途</th></tr></thead><tbody><tr><td><code>dougong_3d_explained_bilingual.mp4</code></td><td>工作区根目录中的三维新版成片，约 {video.stat().st_size/1024/1024:.2f} MiB。</td></tr><tr><td><code>dougong_3d_bilingual_subtitles.srt</code></td><td>工作区根目录中的完整旁白中英字幕。</td></tr><tr><td><code>dougong_3d_report.html</code></td><td>本独立中文报告，含嵌入视频、原图、示例图与源码。</td></tr><tr><td><code>liang_sicheng_dougong/dougong_teaching_model.blend</code></td><td>可编辑的三维模型、材质与关键帧动画。</td></tr><tr><td><code>dougong_explained_bilingual.mp4</code></td><td>二维初版已按用户要求删除；此处仅保留版本记录。</td></tr></tbody></table><h3>依据与适用范围</h3><p>内容依据以用户提供的书页为主。“材”与“出跳”的延伸阅读可见<a href="https://www.jgcm.ac.cn/jah/cn/article/pdf/preview/10.12329/20969368.2021.02007.pdf" target="_blank" rel="noopener">《梁思成与〈营造法式注释〉》</a>。本页外链需联网，报告内的图像与视频不依赖联网。</p><p>模型用于观察构件层次、方向和交叉关系；不能作为修缮设计、精确测绘、榫卯加工或承载能力判断的依据。报告只解读所提供的一页，未推定其具体书页号码、版本或对应建筑实例。</p></section><footer>制作日期：2026 年 9 月 26 日 · 报告语言：中文 · 文件命名：英文 · 独立 HTML 文档</footer></main></body></html>'''
target=ROOT/'dougong_3d_report.html';target.write_text(doc,encoding='utf-8');print('REPORT',target.name,target.stat().st_size)
