from pathlib import Path
from PIL import Image
import json, html, base64
root=Path(__file__).resolve().parent.parent
ns={'__file__':str(root/'scripts'/'render_professional_animation.py')}
source=(root/'scripts'/'render_professional_animation.py').read_text(encoding='utf-8')
exec(source.split("if '--preview' in sys.argv:")[0],ns)
sheet=Image.new('RGB',(1920,1350),ns['PAPER'])
for i in range(19):
    im=ns['frame'](i,4)
    sheet.paste(im.resize((480,270),Image.Resampling.LANCZOS),((i%4)*480,(i//4)*270))
sheet.save(root/'professional_animation/all_scenes_review.png')
data=json.loads((root/'output/storyboard_and_narration.json').read_text(encoding='utf-8-sig'))
poster=base64.b64encode((root/'professional_animation/preview_00.png').read_bytes()).decode()
rows=''.join(f'<tr><td>{i+1:02}</td><td>{html.escape(s[0])}</td><td>{html.escape(s[1])}<br><span>{html.escape(s[2])}</span></td></tr>' for i,s in enumerate(data['scenes']))
report=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>大气环流 · 专业动画制作报告</title><style>body{{margin:0;background:#f5f3ec;color:#203e47;font:16px/1.8 'Microsoft YaHei',sans-serif}}main{{max-width:1100px;margin:auto;padding:50px 28px}}h1{{font-size:48px;line-height:1.2}}h2{{margin-top:42px;border-top:1px solid #d7ded8;padding-top:25px}}video,img{{width:100%;border-radius:15px}}a{{color:#38899a}}blockquote{{border-left:4px solid #d86e48;padding:18px 24px;background:#fffdf6}}.meta,span{{color:#73868a}}table{{border-collapse:collapse;width:100%}}td,th{{padding:14px;text-align:left;vertical-align:top;border-bottom:1px solid #d7ded8}}code{{overflow-wrap:anywhere}}li{{margin:9px 0}}</style><main><p class="meta">ATMOSPHERE / 动画制作记录</p><h1>大气环流<br>专业动画重制版</h1><p>以线稿科学动画为基础，重新设计地球投影、空气流动、分镜构图、字幕阅读节奏和声音层次。</p><p class="meta">1920 × 1080 · 30 fps · 约 3 分 14 秒 · 中文 TTS · 中英字幕</p><video controls preload="metadata" poster="data:image/png;base64,{poster}" src="atmospheric_circulation_studio.mp4"></video><h2>需求与重制目标</h2><blockquote>做一个动画，讲解高中地理知识点“大气环流”。风格轻松有趣，动画格式为线稿，添加合适的音乐，请务必做到引人入胜，字幕用中英双语，解说用TTS</blockquote><blockquote>The animation you build just now too primitive, not up to my standards. I need professional animation.</blockquote><p>原版依赖静态直线箭头和移动图标。重制版以连续粒子流、曲线路径、旋转线框地球、逐步绘制和镜头间柔和转场建立运动语言；保留原有高中地理讲解与中文语音。</p><h2>动画与声音实现</h2><ul><li>地球：经纬线采用球面正交投影，每帧更新自转角度，背面线段隐藏。该地球为示意线框，不包含地理底图。</li><li>空气：沿三次贝塞尔曲线和闭合环流路径运动，带短轨迹与方向箭头。哈德莱、费雷尔、极地环流分别使用暖橙、灰绿、青蓝；费雷尔循环方向与两侧相反。</li><li>叙事：19 个教学分镜，主题高亮、局部淡化、雨滴与季节移动等动态示意。图形在 1—2 秒内逐渐显现，分镜以 0.5 秒缓动交叉淡入衔接。</li><li>字幕：中文按标点拆分为短句，按字数比例分配已有语音段的时长；英文保留完整分镜译文。中文时间轴为近似对齐，并非逐字强制对齐。</li><li>音频：保留已生成的 zh-CN-XiaoxiaoNeural 中文旁白；重新合成和弦变化的轻音乐，双声道输出，并用语音包络降低解说时的背景音量。</li><li>编码：H.264、yuv420p、CRF 18、AAC 192 kbps、faststart。所有帧直接以 1080p、30 fps 生成，无低帧率插帧。</li></ul><h2>科学表述与示意范围</h2><p>三圈环流与气压风带使用理想化纬向平均模型，图中高度和纬度间距不按真实比例。费雷尔环流主要由涡旋活动维持，季节移动及降水差异均为概括性示意。内容核验参考：<a href="https://weather.metoffice.gov.uk/learn-about/weather/atmosphere/global-circulation-patterns">Met Office：全球环流</a>、<a href="https://weather.metoffice.gov.uk/learn-about/weather/atmosphere/intertropical-convergence-zone">Met Office：赤道辐合带</a>。</p><h2>完整分镜与解说</h2><table><tr><th>编号</th><th>主题</th><th>中文旁白 / 英文译文</th></tr>{rows}</table><h2>文件与复现</h2><ul><li><a href="atmospheric_circulation_studio.mp4">新版视频</a></li><li><a href="professional_animation/bilingual_subtitles.srt">双语字幕</a></li><li><a href="scripts/render_professional_animation.py">制作脚本</a></li><li><a href="professional_animation/contact_sheet.png">六幅关键画面</a></li><li><a href="professional_animation/all_scenes_review.png">十九个分镜总览</a></li></ul><p>脚本依赖 Python、Pillow、NumPy 和 imageio-ffmpeg，并读取原版 output 目录下的录音及分镜 JSON。运行 <code>python scripts/render_professional_animation.py</code> 可重新生成成片。</p><h2>检查记录</h2><p id="verification">已生成并检查关键画面与全部分镜缩略图。最终编码与解码检查结果见随视频生成的验证记录。</p></main></html>'''
(root/'atmospheric_circulation_studio_report.html').write_text(report,encoding='utf-8')
print('Review frames and Chinese report generated.')
