Add-Type -AssemblyName System.Speech
$voice = New-Object System.Speech.Synthesis.SpeechSynthesizer
$voice.SelectVoice('Microsoft Zira Desktop')
$voice.Rate = 0
$voice.Volume = 100
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\0-0.wav')
$voice.Speak('A Transformer is a neural network architecture that turns a sequence into useful representations by letting its pieces exchange information.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\0-1.wav')
$voice.Speak('Today, we will follow one tiny message through the machine, and calculate attention ourselves. You only need multiplication, addition, and a little curiosity.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\1-0.wav')
$voice.Speak('Consider the word bank. In the river bank, it means the land beside water. In the bank approved my loan, it means a financial institution.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\1-1.wav')
$voice.Speak('The spelling stays the same. The surrounding words change the meaning. A Transformer builds a different representation of bank in each context.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\2-0.wav')
$voice.Speak('A tokenizer splits text into pieces called tokens. A token can be a word, part of a word, or punctuation. The exact split depends on the tokenizer.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\2-1.wav')
$voice.Speak('Each token gets an integer ID. That ID looks up a learned vector: a list of numbers called an embedding. Our drawings use a few numbers; real models use many more.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\3-0.wav')
$voice.Speak('Imagine an embedding as a location in a high dimensional space. Training adjusts these locations so the network can use them to make predictions.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\3-1.wav')
$voice.Speak('Do not read one coordinate as a neat label like river or money. Useful information is usually spread across many coordinates and interactions.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\4-0.wav')
$voice.Speak('Self attention without position information treats a reordered input as the same collection, with its outputs reordered too. It needs a signal about sequence order.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\4-1.wav')
$voice.Speak('The original Transformer adds positional vectors to embeddings, using sine and cosine waves at different frequencies. Other designs encode position differently. For our tour, token vector plus position vector gives the starting representation.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\5-0.wav')
$voice.Speak('In self attention, every position makes a request and compares it with information offered by other positions in the same sequence.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\5-1.wav')
$voice.Speak('The result is a weighted blend of information. A token can gather useful context from a distant token directly, instead of passing everything along one neighbor at a time.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\6-0.wav')
$voice.Speak('Each input vector is transformed into three vectors. The query is what this position is looking for. A key is what another position can be matched by. A value is the information it can contribute.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\6-1.wav')
$voice.Speak('These are helpful analogies, not literal questions written in English. The vectors come from learned matrix multiplications: Q equals X times W Q, and similarly for K and V.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\7-0.wav')
$voice.Speak('A matrix multiplication forms new coordinates by weighted sums of the old ones. Here, the input one, two becomes the query one, zero with this example matrix.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\7-1.wav')
$voice.Speak('Training learns the entries of those projection matrices. The input changes from sentence to sentence; the learned matrices stay fixed during ordinary generation. Different layers and attention heads have their own projections.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\8-0.wav')
$voice.Speak('Now forget the words for a moment and use three synthetic candidates, A, B, and C. Our query is one, zero. The keys are two, zero; zero, two; and one, one.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\8-1.wav')
$voice.Speak('We also give each candidate a value vector. These invented numbers are chosen for easy arithmetic. They are not measurements from a trained language model.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\9-0.wav')
$voice.Speak('For A, multiply one times two and zero times zero, then add. The score is two. For B, the score is zero. For C, it is one.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\9-1.wav')
$voice.Speak('A larger query key dot product means greater compatibility in the learned representation. It is not automatically a probability, and it depends on vector lengths as well as direction.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\10-0.wav')
$voice.Speak('Our keys have two coordinates, so d k is two. Divide every score by the square root of two. We get approximately one point four one four, zero, and zero point seven zero seven.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\10-1.wav')
$voice.Speak('Why scale? With many roughly independent, zero mean, unit variance coordinates, dot product variance grows with dimension. Scaling helps prevent softmax from becoming excessively sharp and making learning difficult.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\11-0.wav')
$voice.Speak('Softmax exponentiates each score and divides by the sum of those exponentials. For A, e to the power one point four one four is about four point one one three.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\11-1.wav')
$voice.Speak('The three exponentials total about seven point one four one. Our weights are roughly fifty seven point six percent, fourteen percent, and twenty eight point four percent. Every query gets its own recipe.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\12-0.wav')
$voice.Speak('Multiply each value vector by its attention weight, then add the results coordinate by coordinate. A contributes about one point one five two, zero. B contributes zero, zero point two eight zero.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\12-1.wav')
$voice.Speak('C contributes zero point two eight four to each coordinate. The final output is approximately one point four three six, zero point five six four. It is a new vector, not a selected word.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\13-0.wav')
$voice.Speak('Attention of Q, K, and V equals softmax of Q times K transpose, divided by the square root of d k, all multiplied by V.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\13-1.wav')
$voice.Speak('Transpose turns keys into columns so matrix multiplication computes every query key comparison. Softmax runs separately across each row. Multiplying by V blends values for every query at once.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\14-0.wav')
$voice.Speak('For n tokens, Q and K each have n rows and d k columns. Their product gives an n by n score grid. V has n rows and d v columns.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\14-1.wav')
$voice.Speak('The final output has n rows and d v columns: one new vector per token. Attention weights describe information routing. They are not guaranteed explanations of why a model reached a conclusion.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\15-0.wav')
$voice.Speak('One attention head can make only one blend per position. Multiple heads use different learned projections, so they can gather different kinds of information in parallel.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\15-1.wav')
$voice.Speak('Their outputs are concatenated, then mixed by another learned matrix. Heads can discover different patterns, but we do not assign each one a fixed job like grammar or meaning.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\16-0.wav')
$voice.Speak('A Transformer block also contains a feed forward neural network. Attention mixes information across positions; this network transforms each position separately, using the same weights at every position.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\16-1.wav')
$voice.Speak('A common form expands the vector, applies a nonlinear activation, then projects it back. Nonlinearity lets the network build more complex features than a single matrix multiplication can.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\17-0.wav')
$voice.Speak('Residual connections add a sublayer''s update to its input. Instead of replacing the whole representation, each stage can refine it. This also helps gradients flow during training.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\17-1.wav')
$voice.Speak('Layer normalization rescales a token''s features and learns a scale and offset. The original Transformer normalizes after the residual addition; many variants normalize before the sublayer. Stack blocks to repeatedly refine context.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\18-0.wav')
$voice.Speak('An encoder can let every input position see the full input. A decoder for next token generation uses a causal restriction. The original Transformer combines an encoder and a decoder for translation.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\18-1.wav')
$voice.Speak('In that combination, cross attention uses decoder queries with encoder keys and values. Self attention uses one sequence for all three. The same basic attention machinery supports different information flows.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\19-0.wav')
$voice.Speak('To predict the next token after the cat, the decoder must not see that next token. A causal mask blocks attention to later input positions by setting their scores to negative infinity.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\19-1.wav')
$voice.Speak('After softmax, blocked positions get zero weight. A position may still attend to itself and earlier positions. Training shifts the targets by one: each position predicts the following token.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\20-0.wav')
$voice.Speak('The final representation at the last position is projected into one score, or logit, for every token in the vocabulary. Another softmax turns these scores into next token probabilities.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\20-1.wav')
$voice.Speak('The system chooses a token, perhaps by sampling. It appends that token and repeats. These vocabulary probabilities are different from attention weights, which choose how to mix information inside the network.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\21-0.wav')
$voice.Speak('During next token training, the model receives text and predicts the following tokens. Cross entropy penalizes giving low probability to the observed next token: loss equals negative log of its probability.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\21-1.wav')
$voice.Speak('If the correct token gets probability zero point two, the loss is about one point six zero nine. At zero point eight, it is about zero point two two three. Backpropagation computes gradients; an optimizer updates learned weights to reduce average loss.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\22-0.wav')
$voice.Speak('During training, all the correct input tokens are already available, so many positions can be processed in parallel, while a mask prevents cheating. During generation, each new token depends on the previous choices.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\22-1.wav')
$voice.Speak('Full attention compares every pair of positions. Double the sequence length, and the number of pairs quadruples. Efficient implementations reduce memory costs, but long context still requires substantial computation.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\23-0.wav')
$voice.Speak('Here is the journey: tokenize, look up embeddings, add position information, then pass through blocks of attention and feed forward computation with residual connections and normalization.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\23-1.wav')
$voice.Speak('For attention, remember four verbs: compare, scale, normalize, blend. Learned weights make the recipes useful. For generation, project the final vector to vocabulary probabilities, choose a token, and repeat.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\24-0.wav')
$voice.Speak('One final puzzle. Keep our three keys and values, but change the query to zero, one. Which candidate gets the greatest attention weight? Pause and work out the dot products.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\24-1.wav')
$voice.Speak('B now wins: the scores are zero, two, and one. The output flips to approximately zero point five six four, one point four three six. Attention is a context dependent recipe, recalculated from the current vectors. Try it yourself in the companion playground.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\25-0.wav')
$voice.Speak('You have now computed the heart of a Transformer. It is a network that learns how to route and transform information, building representations that help it predict or solve a task.')
$voice.SetOutputToNull()
$voice.SetOutputToWaveFile('C:\MyProjects\TempProject (OpenAI)\transformer-video\audio\25-1.wav')
$voice.Speak('Fluent predictions are not a guarantee of truth. But the mechanism is something you can understand: vectors, comparisons, weighted sums, and learned transformations, repeated at scale.')
$voice.SetOutputToNull()
$voice.Dispose()
